SET(CMAKE_CXX_STANDARD 17)
SET(CMAKE_CXX_STANDARD_REQUIRED ON)

SET(CMAKE_BINARY_DIR_INCLUDE ${CMAKE_BINARY_DIR}/include)
INCLUDE_DIRECTORIES(AFTER ${CMAKE_BINARY_DIR_INCLUDE})

IF (CYWIN OR WIN32)
    ADD_DEFINITIONS(-DWIN32 -D_WIN32)
    SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
    SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
    SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
ELSE()
    SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib)
    SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
    SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin)
ENDIF()

LINK_DIRECTORIES(AFTER ${CMAKE_ARCHIVE_OUTPUT_DIRECTORY})

SET_PROPERTY(GLOBAL PROPERTY AUTOGEN_SOURCE_GROUP "AutoGen")
SET_PROPERTY(GLOBAL PROPERTY USE_FOLDERS ON)
SET_PROPERTY(GLOBAL PROPERTY PREDEFINED_TARGETS_FOLDER "CMakePreDef")